// Exports what the firmware's offline calendar needs (../firmware/src/calendar_data.h), from
// the same sources the server renders with, so the device draws the same pixels:
//  - lunar months (start day, month, leap, lunar year) and solar-term days, 2025-2074,
//    from lunar-javascript;
//  - the official holidays bundled here (assets/holidays, holiday-cn);
//  - the glyphs of every character the calendar can print, from the reference fonts.
//
//   npx tsx scripts/export-firmware-calendar.ts [../firmware/src/calendar_data.h]
import { writeFileSync } from "node:fs";
import lunarPkg from "lunar-javascript";
import { refFonts } from "../src/render/reftext.js";
import { glyphFor } from "../src/render/bdf.js";
import {
  WEEKDAY, LUNAR_MONTH, LUNAR_DATE, GAN, ZHI, lunarOf, festivalOf, holidayOf, loadedHolidayYears,
} from "../src/data/calendar.js";

const { Solar } = lunarPkg;
const FIRST = 2025, LAST = 2074;
const out = process.argv[2] ?? new URL("../../firmware/src/calendar_data.h", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");

const dayNum = (y: number, m: number, d: number) => Math.round(Date.UTC(y, m - 1, d) / 86_400_000);
const EPOCH = dayNum(FIRST, 1, 1);

// ── lunar months: one entry per month start (plus the month running on Jan 1 of FIRST) ──
const months: { start: number; month: number; leap: boolean; year: number }[] = [];
let lunarYear = 0;
for (let dn = EPOCH; dn <= dayNum(LAST, 12, 31); dn++) {
  const dt = new Date(dn * 86_400_000);
  const l = Solar.fromYmd(dt.getUTCFullYear(), dt.getUTCMonth() + 1, dt.getUTCDate()).getLunar();
  const m = l.getMonth();
  if (dn === EPOCH || l.getDay() === 1) {
    lunarYear = l.getYear();
    months.push({ start: dn === EPOCH ? dn - (l.getDay() - 1) : dn, month: Math.abs(m), leap: m < 0, year: lunarYear });
  }
}

// ── solar terms: two per Gregorian month, term k (0 = 小寒) in month k/2 + 1 ──
const termNames: string[] = new Array(24).fill("");
const termDays: number[][] = [];
for (let y = FIRST; y <= LAST; y++) {
  const row: number[] = new Array(24).fill(0);
  for (let m = 1; m <= 12; m++) {
    let k = (m - 1) * 2;
    const dim = new Date(Date.UTC(y, m, 0)).getUTCDate();
    for (let d = 1; d <= dim; d++) {
      const name = lunarOf(y, m, d).jieqi;
      if (!name) continue;
      if (termNames[k] && termNames[k] !== name) throw new Error(`term ${k}: ${termNames[k]} vs ${name} (${y}-${m}-${d})`);
      termNames[k] = name;
      row[k++] = d;
    }
    if (k !== m * 2) throw new Error(`${y}-${m}: expected two solar terms`);
  }
  termDays.push(row);
}

// ── holidays: day (since EPOCH) and off / work ──
const holidayYears = loadedHolidayYears().sort();
const holidays: { day: number; off: boolean }[] = [];
for (const y of holidayYears) {
  for (let dn = dayNum(y, 1, 1); dn <= dayNum(y, 12, 31); dn++) {
    const dt = new Date(dn * 86_400_000);
    const h = holidayOf(dt.getUTCFullYear(), dt.getUTCMonth() + 1, dt.getUTCDate());
    if (h) holidays.push({ day: dn - EPOCH, off: h === "off" });
  }
}

// ── characters the calendar prints, per font ──
const cjk = new Set<string>();
const add = (s: string) => { for (const ch of s) cjk.add(ch); };
[...WEEKDAY, ...LUNAR_MONTH, ...LUNAR_DATE, ...termNames, "年月闰周休班 []"].forEach(add);
"鼠牛虎兔龙蛇马羊猴鸡狗猪".split("").forEach(add);
for (let y = FIRST; y <= LAST; y++) for (let m = 1; m <= 12; m++) {
  const dim = new Date(Date.UTC(y, m, 0)).getUTCDate();
  for (let d = 1; d <= dim; d++) {
    const l = lunarOf(y, m, d);
    add(l.yearGanZhi + l.zodiac);
    add(festivalOf(y, m, d, l) ?? "");
  }
}
const digits = "0123456789";
const wqySet = [...cjk].join("") + digits + ".V";
const F = refFonts();
const fontDefs: [string, typeof F.wqy12, string][] = [
  ["helvB18", F.helvB18, digits], ["helvB14", F.helvB14, digits],
  ["wqy12", F.wqy12, wqySet], ["wqy9", F.wqy9, wqySet], ["wqy6", F.wqy6, GAN.join("") + ZHI.join("") + "清"], // 清: its width spaces the stacked day stem/branch
];

let src = `// Generated by server/scripts/export-firmware-calendar.ts -- do not edit.
// Offline calendar data: lunar months and solar terms ${FIRST}-${LAST} (lunar-javascript),
// official holidays ${holidayYears.join(", ")} (holiday-cn), glyphs of the reference fonts.
#pragma once
#include <stdint.h>

#define CAL_FIRST_YEAR ${FIRST}
#define CAL_LAST_YEAR ${LAST}
// day number (days since 1970-01-01) of ${FIRST}-01-01; table days count from here
#define CAL_EPOCH_DAY ${EPOCH}

// a lunar month: first day (since CAL_EPOCH_DAY), month 1-12 (| 0x80 = leap), lunar year - 2000
struct CalLunarMonth { int16_t start; uint8_t month; uint8_t year; };
static const CalLunarMonth CAL_LUNAR_MONTHS[] = {
${months.map((x) => `  {${x.start - EPOCH}, ${x.month | (x.leap ? 0x80 : 0)}, ${x.year - 2000}}`).join(",\n")}
};
static const int CAL_LUNAR_MONTH_COUNT = ${months.length};

// solar terms: [year - CAL_FIRST_YEAR][k] = day of month of term k (in month k / 2 + 1)
static const char *const CAL_TERM_NAMES[24] = { ${termNames.map((n) => `"${n}"`).join(", ")} };
static const uint8_t CAL_TERM_DAYS[${LAST - FIRST + 1}][24] = {
${termDays.map((r) => `  {${r.join(",")}}`).join(",\n")}
};

// official holidays: day since CAL_EPOCH_DAY | 0x8000 when it is a make-up work day (班)
static const uint16_t CAL_HOLIDAYS[] = {
${chunk(holidays.map((h) => String(h.day | (h.off ? 0 : 0x8000))), 16).map((l) => "  " + l.join(", ")).join(",\n")}
};
static const int CAL_HOLIDAY_COUNT = ${holidays.length};
// years the bundled holidays cover (bit y - CAL_FIRST_YEAR)
static const uint64_t CAL_HOLIDAY_YEARS = ${holidayYears.reduce((m, y) => m | (1n << BigInt(y - FIRST)), 0n)}ULL;

// glyphs: code point, advance, bitmap box (w, h, x / y offset from the origin), offset of
// the rows (MSB first, (w + 7) / 8 bytes each) in the font's bits; sorted by code point
struct CalGlyph { uint16_t cp; int8_t adv; uint8_t w, h; int8_t xo, yo; uint16_t off; };
struct CalFont { const CalGlyph *glyphs; uint16_t count; const uint8_t *bits; int8_t ascent, descent; };
`;

for (const [name, rf, chars] of fontDefs) {
  const cps = [...new Set([...chars].map((c) => c.codePointAt(0)!))].sort((a, b) => a - b);
  const bits: number[] = [];
  const entries: string[] = [];
  for (const cp of cps) {
    const g = glyphFor(rf.f, cp);
    if (!g || !rf.f.glyphs.has(cp)) throw new Error(`${name}: no glyph for ${String.fromCodePoint(cp)}`);
    const nb = Math.ceil(g.w / 8);
    entries.push(`{${cp}, ${g.advance}, ${g.w}, ${g.h}, ${g.xOff}, ${g.yOff}, ${bits.length}}`);
    for (const row of g.rows) {
      // rows hold w bits (MSB = first pixel); left-align them into whole bytes
      const v = row << BigInt(nb * 8 - g.w);
      for (let b = nb - 1; b >= 0; b--) bits.push(Number((v >> BigInt(b * 8)) & 0xffn));
    }
  }
  src += `\nstatic const uint8_t CAL_${name}_BITS[] = {\n${chunk(bits.map((b) => "0x" + b.toString(16).padStart(2, "0")), 24).map((l) => "  " + l.join(",")).join(",\n")}\n};\n`;
  src += `static const CalGlyph CAL_${name}_GLYPHS[] = {\n${chunk(entries, 6).map((l) => "  " + l.join(", ")).join(",\n")}\n};\n`;
  src += `static const CalFont CAL_${name} = { CAL_${name}_GLYPHS, ${cps.length}, CAL_${name}_BITS, ${rf.ascent}, ${rf.descent} };\n`;
  console.log(`${name}: ${cps.length} glyphs, ${bits.length} bytes`);
}

writeFileSync(out, src.replace(/\r/g, ""));
console.log(`${months.length} lunar months, ${holidays.length} holidays (${holidayYears.join(", ")}) -> ${out}`);

function chunk<T>(a: T[], n: number): T[][] {
  const r: T[][] = [];
  for (let i = 0; i < a.length; i += n) r.push(a.slice(i, i + n));
  return r;
}
