"""
Builds src/cert_bundle.cpp: the root certificates the firmware trusts for HTTPS, in the
ESP-IDF certificate-bundle format that WiFiClientSecure::setCACertBundle() reads
(2-byte count, then per root: 2-byte subject length, 2-byte key length, subject DER,
public-key DER; sorted by subject, since the device binary-searches the issuer).

Only the subject and public key of each root are kept (~450 bytes a root), and during a
TLS handshake the device looks up just the one root the server's chain needs.

Input: every *.cer / *.der / *.pem in tools/certs/ (public root certificates; add one by
dropping its file there). Each must be a self-signed CA certificate, valid for a while.

    python tools/make_cert_bundle.py          (needs the `cryptography` package)
"""
import datetime, glob, hashlib, os
from cryptography import x509
from cryptography.hazmat.primitives import serialization

HERE = os.path.dirname(os.path.abspath(__file__))
CERTS = os.path.join(HERE, "certs")
OUT = os.path.join(HERE, "..", "src", "cert_bundle.cpp")
VALID_UNTIL = datetime.datetime(2027, 1, 1, tzinfo=datetime.timezone.utc)


def load(path):
    data = open(path, "rb").read()
    return x509.load_pem_x509_certificate(data) if b"-----BEGIN" in data else x509.load_der_x509_certificate(data)


def main():
    roots = []
    for path in sorted(glob.glob(os.path.join(CERTS, "*"))):
        if not path.lower().endswith((".cer", ".der", ".pem", ".crt")):
            continue
        c = load(path)
        name = os.path.basename(path)
        bc = c.extensions.get_extension_for_class(x509.BasicConstraints).value
        assert bc.ca, f"{name}: not a CA certificate"
        assert c.issuer == c.subject, f"{name}: not self-signed (a root)"
        assert c.not_valid_after_utc > VALID_UNTIL, f"{name}: expires {c.not_valid_after_utc:%Y-%m-%d}"
        subject = c.subject.public_bytes()
        key = c.public_key().public_bytes(serialization.Encoding.DER, serialization.PublicFormat.SubjectPublicKeyInfo)
        roots.append((subject, key, name, c))
    roots.sort(key=lambda r: r[0])
    assert len({r[0] for r in roots}) == len(roots), "two roots with the same subject"

    blob = bytearray(len(roots).to_bytes(2, "big"))
    for subject, key, _, _ in roots:
        blob += len(subject).to_bytes(2, "big") + len(key).to_bytes(2, "big") + subject + key

    lines = [", ".join(f"0x{b:02x}" for b in blob[i:i + 20]) for i in range(0, len(blob), 20)]
    listing = "\n".join(
        f"//   {r[3].subject.rfc4514_string()[:70]:<70}  until {r[3].not_valid_after_utc:%Y-%m}  sha1 {hashlib.sha1(r[3].public_bytes(serialization.Encoding.DER)).hexdigest()[:16]}"
        for r in roots)
    src = f"""// Generated by tools/make_cert_bundle.py from tools/certs/ -- do not edit.
// Root certificates trusted for HTTPS ({len(roots)}, {len(blob)} bytes):
{listing}
#include "cert_bundle.h"

const uint8_t CERT_BUNDLE[] = {{
  {(","+chr(10)+"  ").join(lines)}
}};

void setTrustedRoots(WiFiClientSecure &client) {{ client.setCACertBundle(CERT_BUNDLE); }}
"""
    open(OUT, "w", encoding="utf-8", newline="\n").write(src)
    print(f"{len(roots)} roots, {len(blob)} bytes -> {OUT}")


if __name__ == "__main__":
    main()
